workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-v10
      - node-v12

version: 2
jobs:
  node-base: &node-base
    docker:
      - image: node:latest
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-cache-master-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Test
          command: npm test
      - run:
          name: Test in the oldest Google Closure Tools
          command: |
            CLOSURE_VER=20190325
            npm i "google-closure-deps@${CLOSURE_VER}"
            npm run unit
      - run:
          name: Report coverage to coveralls.io
          command: |
            if [ "$CIRCLE_JOB" = 'node-v12' ]; then
              npm run coveralls
            else
              echo "Skip reporting coverage"
            fi
      - save_cache:
          key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

  node-v10:
    <<: *node-base
    docker:
      - image: node:10
  node-v12:
    <<: *node-base
    docker:
      - image: node:12
