version: 2.1

workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-v10
      - node-v12

commands:
  early_return_for_forked_pull_requests:
    description: >-
      If this build is from a fork, stop executing the current job and return success.
      This is useful to avoid steps that will fail due to missing credentials.
      See https://circleci.com/blog/continuous-deployment-of-an-express-graphql-server-to-heroku/
    steps:
      - run:
          name: Early return if this build is from a forked PR
          command: |
            if [ -n "$CIRCLE_PR_NUMBER" ]; then
              echo "Nothing to do for forked PRs, so marking this step successful"
              circleci step halt
            fi

jobs:
  node-base: &node-base
    docker:
      - image: node:latest
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-cache-master-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Test
          command: npm test
      - run:
          name: Test in the oldest Google Closure Tools
          command: |
            CLOSURE_VER=20190325
            npm i "google-closure-deps@${CLOSURE_VER}"
            npm run unit
      - save_cache:
          key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - early_return_for_forked_pull_requests
      - run:
          name: Report coverage to coveralls.io
          command: |
            if [ "$CIRCLE_JOB" = 'node-v12' ]; then
              npm run coveralls
            else
              echo "Skip reporting coverage"
            fi

  node-v10:
    <<: *node-base
    docker:
      - image: node:10
  node-v12:
    <<: *node-base
    docker:
      - image: node:12
